print("open cabinet")
print("procure plate from cabinet")
print("close cabinet")
print("place plate on table or counter")
print("open drawer")
print("procure knife from drawer")
print("close drawer")
print("place knife on plate")
print("open refrigerator")
print("procure bread loaf from refrigerator")
print("open bread loaf")
print("remove one slice of bread from loaf")
print("place one slice of bread on plate")
print("remove one slice of bread from loaf")
print("place one slice of bread on plate")
print("close bread loaf")
print("return bread loaf to refrigerator")
print("procure jelly jar from refrigerator")
print("procure peanut butter jar from refrigerator")
print("close refrigerator")
print("place jelly jar on table or counter")
print("open peanut butter jar")
print("place peanut butter jar lid on table or counter")
print("pick up knife off plate")
print("remove sufficient peanut butter from jar using knife")
print("apply peanut butter to one piece of bread using knife")
print("place peanut butter jar on table or counter")
print("wipe off knife on clean piece of bread")
print("place knife on plate")
print("screw peanut butter lid on to jar")
print("open jelly jar")
print("place jelly jar lid on table or counter")
print("pick up knife off of the plate")
print("remove sufficient jelly from jar using knife")
print("apply jelly to the one piece of semi-clean bread using knife")
print("place jelly jar on table or counter")
print("place knife in sink")
print("screw lid on to jelly jar")
print("open refrigerator")
print("place jelly jar in refrigerator")
print("place peanut butter jar in refrigerator")
print("close refrigerator")
print("combine piece of bread covered in peanut butter with piece of bread covered in jelly")
print("place completed peanut butter and jelly sandwich onto plate")
